-- Tabela de Usuarios
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TBL_USUARIO (
    ID_USUARIO INTEGER DEFAULT SEQ_USUARIO.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    SENHA VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(5) DEFAULT 'USER'
);

ALTER TABLE TBL_USUARIO
ADD CONSTRAINT email_unico UNIQUE (EMAIL);

-- Tabela de Transportes
CREATE SEQUENCE SEQ_TRANSPORTE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TBL_TRANSPORTE (
    ID_TRANSPORTE INTEGER DEFAULT SEQ_USUARIO.NEXTVAL NOT NULL,
    MODELO VARCHAR2(100) NOT NULL,
    TIPO_COMBUSTIVEL VARCHAR2(100) NOT NULL,
    KM_POR_LITRO NUMBER(3,1) NOT NULL,
    ULTIMA_MANUTENCAO DATE
);