-- Tabela de Transportes Sustentáveis
CREATE TABLE transportes_sustentaveis (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(255) NOT NULL,
    descricao VARCHAR2(500),
    PRIMARY KEY (id)
);

-- Tabela de Impactos Ambientais
CREATE TABLE impacto_transporte (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    empresa_id NUMBER NOT NULL,
    impacto_descricao VARCHAR2(500),
    impacto_valor NUMBER,
    PRIMARY KEY (id)
);

-- Tabela de Recompensas
CREATE TABLE recompensas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    descricao VARCHAR2(255),
    valor NUMBER NOT NULL,
    PRIMARY KEY (id)
);
