-- Tabela de Usuarios
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TBL_USUARIO (
    ID_USUARIO INTEGER DEFAULT SEQ_USUARIO.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    SENHA VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(5) DEFAULT 'USER',

    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)
);

ALTER TABLE TBL_USUARIO
ADD CONSTRAINT email_unico UNIQUE (EMAIL);

-- Tabela de Transportes
CREATE SEQUENCE SEQ_TRANSPORTE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TBL_TRANSPORTE (
    ID_TRANSPORTE INTEGER DEFAULT SEQ_USUARIO.NEXTVAL NOT NULL,
    MODELO VARCHAR2(100) NOT NULL,
    TIPO_COMBUSTIVEL VARCHAR2(100) NOT NULL,
    KM_POR_LITRO NUMBER(3,1) NOT NULL,
    ULTIMA_MANUTENCAO DATE,

    CONSTRAINT PK_TRANSPORTE PRIMARY KEY (ID_TRANSPORTE)
);

-- Tabela de Funcionarios
CREATE SEQUENCE SEQ_FUNCIONARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TBL_FUNCIONARIO (
    ID_FUNCIONARIO INTEGER DEFAULT SEQ_FUNCIONARIO.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    TRANSPORTE_ALTERNATIVO CHAR(1) NOT NULL,
    VEICULO_CORPORATIVO CHAR(1) NOT NULL,

    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID_FUNCIONARIO)
);

-- Tabela de Uso de Transportes
CREATE SEQUENCE SEQ_USO_TRANSPORTE_FUNCIONARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TBL_USO_TRANSPORTE_FUNCIONARIO (
    ID_USO_TRANSPORTE_FUNCIONARIO INTEGER DEFAULT SEQ_USO_TRANSPORTE_FUNCIONARIO.NEXTVAL NOT NULL,
    ID_TRANSPORTE INTEGER NOT NULL,
    ID_FUNCIONARIO INTEGER NOT NULL,
    DATA_USO DATE NOT NULL,
    KM_RODADO NUMBER(6,1) NOT NULL,

    CONSTRAINT FK_USO_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES TBL_FUNCIONARIO(ID_FUNCIONARIO),
    CONSTRAINT FK_USO_TRANSPORTE FOREIGN KEY (ID_TRANSPORTE) REFERENCES TBL_TRANSPORTE(ID_TRANSPORTE),
    CONSTRAINT PK_USO_TRANSPORTE_FUNCIONARIO PRIMARY KEY (ID_USO_TRANSPORTE_FUNCIONARIO)
);

-- Tabela de Metas Ambientais
CREATE SEQUENCE SEQ_META_AMBIENTAL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TBL_META_AMBIENTAL (
    ID_META_AMBIENTAL INTEGER DEFAULT SEQ_USO_TRANSPORTE_FUNCIONARIO.NEXTVAL NOT NULL,
    ID_TRANSPORTE INTEGER NOT NULL,
    DESCRICAO VARCHAR2(1000),
    MAX_KM_POR_MES NUMBER(7,1),

    CONSTRAINT FK_META_TRANSPORTE FOREIGN KEY (ID_TRANSPORTE) REFERENCES TBL_TRANSPORTE(ID_TRANSPORTE),
    CONSTRAINT PK_META_AMBIENTAL PRIMARY KEY (ID_META_AMBIENTAL)
);

-- Tabela de Recompensas
CREATE SEQUENCE SEQ_RECOMPENSA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TBL_RECOMPENSA (
    ID_RECOMPENSA INTEGER DEFAULT SEQ_RECOMPENSA.NEXTVAL NOT NULL,
    ID_FUNCIONARIO INTEGER NOT NULL,
    DESCRICAO VARCHAR2(1000) NOT NULL,
    VALOR NUMBER(7,2) NOT NULL,

    CONSTRAINT FK_RECOMPENSA_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES TBL_FUNCIONARIO(ID_FUNCIONARIO),
    CONSTRAINT PK_RECOMPENSA PRIMARY KEY (ID_RECOMPENSA)
);