version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
      SPRING_DATASOURCE_USERNAME: rm556002
      SPRING_DATASOURCE_PASSWORD: 240605
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
    depends_on: []
volumes: {}